# Generated by Django 3.2 on 2022-08-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
