# Generated by Django 3.2 on 2022-02-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='store',
            name='district',
        ),
    ]
