# Generated by Django 3.2 on 2022-02-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220215_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='province_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='regency_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
