# Generated by Django 3.2 on 2022-02-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220217_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='postal_code',
        ),
    ]
