# Generated by Django 3.2 on 2022-03-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(default='toko', max_length=255),
            preserve_default=False,
        ),
    ]
