# Generated by Django 3.2 on 2022-01-08 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_price'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartDetails',
            new_name='CartDetail',
        ),
    ]
