# Generated by Django 3.2 on 2022-01-08 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20220108_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartdetail',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
