# Generated by Django 3.2 on 2022-09-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_flashsale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
