# Generated by Django 3.2 on 2022-09-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_flashsale_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashsale',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='flashsale',
            name='price',
        ),
    ]
