# Generated by Django 3.2 on 2022-09-17 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20220917_1504'),
        ('store', '0012_alter_store_id'),
        ('core', '0004_auto_20220917_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flash_products', to='store.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flash_products', to='product.product'),
        ),
    ]
